### ISSUE TITLE
Currency library

### ISSUE THREAD

**Issue by lpil** [gleam-lang/suggestions#36]

**Comment by CrowdHailer** [comment]
Can you explain more the aim of this issue. How does it differ from wrapping proc_lib?

**Comment by lpil** [comment]
This is a library for safely representing currencies such as dollars and pounds sterling.

**Comment by davecaos** [comment]
I read concurrency instead of currency too 😺 !
At least I know int types on The Beam could go really big, but no the float ones or also you can lose precision.
Maybe separate the value in two parts to avoid any kind of misrepresentation, something like a type that can grows more than a double float.

 ```rust
pub type Money{
  Money(name: String, unit: Int, cents :Int)
}
 ```

**Comment by inoas** [comment]
Couldn't this be a library for decimals instead (with garantueed decimals/precision) and another for number and currency formatting?

**Comment by lpil** [comment]
Decimals could be a useful part of a currency library but there's likely other features that will be desired as well. i.e. which currency is being used.

**Comment by benmyles** [comment]
Working on this here: https://github.com/benmyles/gleam_money.

**Comment by lpil** [comment]
Wonderful!
