### ISSUE TITLE
Json library

### ISSUE THREAD

**Issue by lpil** [gleam-lang/suggestions#9]
Simplest path: bindings to jsx.

We could create bindings to Jiffy, which is much faster but requires C compilation to use.

Hardest but possibly most beneficial path: Fork Jason, strip out the protocols and Elixir specific bits, then decompile to Erlang and write bindings. This would us a very fast pure Erlang Json library without the Elixir dependency.

**Comment by gamebox** [comment]
Is there something undesirable about a pure gleam implementation?  If so, that's fine, I think there is a lot of Jason's implementation that would be tough to create bindings that would feel idiomatic in gleam.

**Comment by lpil** [comment]
I would like to wrap an existing JSON library.

Jason is great but unsuitable as it has a dependency on the Elixir compiler and standard library, a similar Erlang library would be better.

**Comment by rjdellecese** [comment]
I'm writing bindings to [`jsone`](https://github.com/sile/jsone); you can track the progress [here](https://github.com/rjdellecese/jsone_gleam). I chose `jsone` because it's fast and simple (has a small API), and is written in Erlang.

As I'm envisioning it, decoding will work as Louis describes above, and the user can then use a library like [`gleam_decode`](https://github.com/rjdellecese/gleam_decode) to decode the successful result. I considered writing a set of "decoders" specifically for operating on JSON values (instead of `Dynamic` values, as `gleam_decode` does), but I wasn't sure that any transparency that might add to the experience would be worth the almost-but-not-necessarily-exactly-the-same duplication between those two different decoding APIs. Another (not mutually-exclusive) option I considered was decoding JSON into a tree of `JsonValue` types, e.g.

```rust
pub type JsonNumber {
  JsonInt(Int)
  JsonFloat(Float)
};

pub type JsonValue {
  JsonString(String)
  JsonNumber(JsonNumber)
  JsonArray(List(JsonValue))
  JsonBool(Bool)
  JsonNull
  JsonObject(List(tuple(String, JsonValue)))
}
```

but I wasn't convinced that that would provide a better experience than the decoder approach, or that it's addition to the decoder approach would add any benefit.

If anyone has any feedback on the library or my approach as outlined above, I'd love to hear it! Feel free to open an issue over in the [`jsone_gleam`](https://github.com/rjdellecese/jsone_gleam) repo for discussion, as well.

**Comment by lpil** [comment]
Thanks for sharing the project!

JSON decoding is an area where we care about performance so I think that using `Dynamic` over a `JsonValue` would be a better fit, even though it is less precise (as Dynamic can represent any term, while JsonValue can only represent JSON).

 A couple of nitpicks:

It would be nice if the library didn't depend upon any particular decoding library, leaving that up to the user.

It would be useful if the library returned the reason for the parse failure when it does not succeed.

For naming conventions, I'm trying to have Gleam hex packages start with the prefix `gleam_` so I would go for the name `gleam_jsone` and use the module name `gleam/jsone` as it's a wrapper around an existing library.

**Comment by rjdellecese** [comment]
> It would be nice if the library didn't depend upon any particular decoding library, leaving that up to the user.

Currently, the only public functions are:

```rust
decode_json(json: String) -> Result(Dynamic, String)
```

and

```rust
encode_json(json_value: JsonValue) -> Result(Dynamic, String)
```

so there is no requirement that the user themselves use any particular decoding library. I'm only using `gleam_decode` for the binding library's own internal purposes. Or are you saying that it would be nice if the binding library had no additional dependencies beyond the `jsone` Erlang lib?

> It would be useful if the library returned the reason for the parse failure when it does not succeed.

Agreed, I definitely plan on adding more specific failure messages!

> For naming conventions, I'm trying to have Gleam hex packages start with the prefix `gleam_` so I would go for the name `gleam_jsone` and use the module name `gleam/jsone` as it's a wrapper around an existing library.

Sounds good, will do!

**Comment by lpil** [comment]
https://github.com/rjdellecese/gleam_jsone
